---

- hosts: "{{ sw }}"
  gather_facts: no
  ignore_errors: yes
  serial: 1

  tasks:

    - name: Execute IOS commands
      ios_banner:
        banner: "{{ type }}"
        text: |
          "{{ banner }}"
        state: present
      register: commands_output
