---

- hosts: "{{ sw }}"
  gather_facts: no
  ignore_errors: yes
  serial: 1

  tasks:

    - name: Execute IOS commands
      ios_config:
         lines: "{{ command_config }}"
      register: commands_output

