---

- hosts: "{{ sw }}"
  gather_facts: no
  ignore_errors: yes
  serial: 1

  tasks:

    - name: Execute IOS commands
      ios_banner:
        banner: motd
        text: |
          Junk login banner
            multi (this one with two spaces indentation)
              line (this one with 4 spaces indentation)
          ! (this one with no indentation at all)
        state: present
      register: commands_output
