---

- hosts: "{{ sw }}"
  connection: network_cli
  gather_facts: no

tasks:

  - name: "Execute DellOS commands"
    dellos6_config:
      commands: ["{{ command_config }}"]
    register: set_hostname
