---

- hosts: "{{ sw }}"
  gather_facts: no
  ignore_errors: yes
  serial: 1

  tasks:

    - name: Execute IOS commands
      dellos6_command:
         commands: "{{ command_show }}"
      register: commands_output
