---

- hosts: "{{ sw }}"
  connection: network_cli
  gather_facts: no

  tasks:
  - name: "Execute DellOS commands"
    dellos6_config:
      parents: logging 192.168.10.73
      commands: ["{{ command_config }}"]
    register: commands_output
