---

- hosts: "{{ sw }}"
  connection: network_cli
  gather_facts: no

  tasks:
  - name: "Execute DellOS commands"
    dellos6_config:
      parents: ["{{ command_config }}"]
      lines:
        - "{{ parents }}"
        
    register: commands_output
