---

- hosts: "{{ sw }}"
  connection: network_cli
  gather_facts: no

  tasks:
  - name: "Execute DellOS commands"
    dellos6_config:
      parents: ["{{ parents }}"]
      lines:
        - "{{ command_config }}"
        
    register: commands_output
