---

- hosts: "{{ sw }}"
  gather_facts: no
  ignore_errors: yes
  roles:
    - Juniper.junos

  tasks: 
    - name: Execute JunOS commands
       juniper_junos_config
         lines
         - "{{ command_config }}"
       register commands_output


