---

- hosts: "{{ sw }}"
  gather_facts: no
  ignore_errors: yes
  roles:
    - Juniper.junos
    
  tasks:
   - name: Execute JunOS commands
      ios_command:
         lines: 
         - "{{ command_config }}"
      register: commands_output
