---
- name: Test juniper_junos_config module
  hosts: "{{ sw }}"
  connection: local
  gather_facts: no
  collections:
    - juniper.device
  tasks:
#################
  - name: Append .foo to the hostname using private config mode.
      junipernetworks.junos.junos_config:
        config_mode: 'private'
        load: 'merge'
        lines:
          - "{{ command_config }}"
        comment: "Append .foo to the hostname"
      ignore_errors: True
